### ISSUE TITLE
Call for maintainer(s)

### ISSUE THREAD

**Issue by getreu** [utopiabound/grpn#10]
I'm looking for a maintainer for this project. My focus is elsewhere right now. 

Please prove your motivation and availability by fixing #11 .

**Comment by getreu** [comment]
News here?

**Comment by getreu** [comment]
@utopiabound : I would like to transfer you the ownership of this project on 1.1.2019 if it is Ok for.

**Comment by utopiabound** [comment]
@getreu, That works for me.

**Comment by getreu** [comment]
I have been maintaining Paul Wilkins' GRPN calculator  for 10 years now. First it was hosted on SourceForge, then it moved to Github. During these years GRPN has seen many improvements, i.e. eng-mode, Pango-fonts, clipboard support and new functions. Today, this GRPN branch is upstream for all major GRPN-distributions. 
Nathaniel Clark started to contribute to GRPN in 2013. From the beginning I always apprechiated his his high quality and stable commits. He knows the code well and I am happy that he accepted to take over this little nice project. The transfer allows me to free resources for my upcoming new challanges.
I wish him good luck and success. 
JG

**Comment by utopiabound** [comment]
@getreu, I've moved that fork out of the way.

**Comment by getreu** [comment]
The transfer still does not work. Github tells me:

>   utopiabound already has a repository in the getreu/grpn network

**Comment by utopiabound** [comment]
Okay, I've deleted the old repo.  It should work now *crosses-fingers*
